version: "3.9"

services:
  db:
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  model-serving:
    image: asdkant/fastapi-hello-world
    ports:
      - "81:80"
  jupyter:
    image: jupyter/scipy-notebook:python-3.9.10
    ports:
      - "10001:8888"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./:/home/jovyan/project
  
  